version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: subscription-service-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subscription_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - subscription-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  subscription-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: subscription-service-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: subscription_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - subscription-network
    restart: on-failure

networks:
  subscription-network:
    driver: bridge

volumes:
  postgres-data:
